<?php

/**
 * @file
 * Hook implementations, callbacks form OpenID SSO.
 */

/**
 * Implementation of hook_menu().
 */
function openid_sso_menu() {
  $items = array();
  // Move log in page to login/direct. See how openid_sso_menu_alter() replaces
  // log in.
  $items['login/direct'] = array(
    'title' => 'Direct log in',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_login'),
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
  );
  $items['sso/init'] = array(
    'page callback' => 'openid_sso_init_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['admin/user/openid-sso'] = array(
    'title' => 'OpenID Simple Sign-On',
    'description' => 'Configure a designated OpenID provider for simplified OpenID-based sign-on.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openid_sso_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_menu_alter().
 */
function openid_sso_menu_alter(&$items) {
  $items['user']['page callback'] = 'openid_sso_user_page';
  $items['user/register']['page callback'] = 'openid_sso_user_page';
  $items['user/password']['page callback'] = 'openid_sso_user_page';
  $items['user/%user_category/edit']['access callback'] = 'openid_sso_user_edit_access';
  $items['user/%user_uid_optional']['page callback'] = 'openid_sso_user_view';
  $items['logout']['page callback'] = 'openid_sso_logout_page';
}

/**
 * Implementation of hook_form_alter().
 */
function openid_sso_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    // Redirect user to front page after login, otherwise she will be pushed to
    // OP when using the login/direct form.
    case 'user_login':
      $form['#redirect'] = '';
      break;
    // Don't allow the user to login using the login block. Direct her to OP
    // instead.
    case 'user_login_block':
      // Remove all child elements.
      foreach (element_children($form) as $key) {
        unset($form[$key]);
      }
      $form['#action'] = url('user');
      $form['#validate'] = array();
      if ($provider = variable_get('openid_sso_provider', array())) {
        $form['message'] = array(
          '#type' => 'item',
          '#value' => t('Login using @provider_name as your OpenID provider.', array('@provider_name' => $provider['name'])),
        );
        $form['submit'] = array(
          '#type' => 'submit',
          '#value' => t('Login'),
          '#submit' => array('openid_sso_user_login_submit'),
        );
      }
      break;
  }
}

/**
 * Implementation of hook_requirements().
 */
function openid_sso_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime') {
    $requirements['bcmath']['title'] = t('BC Math');
    if (extension_loaded('bcmath')) {
      $requirements['bcmath']['description'] = t('The !bcmath PHP extension is present.', array('!bcmath' => l('BC Math', 'http://www.php.net/manual/en/book.bc.php')));
    }
    else {
      $requirements['bcmath']['description'] = t('The !bcmath PHP extension is missing. OpenID Simple Sign-On is not working.', array('!bcmath' => l('BC Math', 'http://www.php.net/manual/en/book.bc.php')));
      $requirements['bcmath']['severity'] = REQUIREMENT_ERROR;
    }
  }
  return $requirements;
}

/**
 * Custom access callback, only allow users with 'administer users' permissions
 * to edit a user on relying party. Redirect all other users.
 */
function openid_sso_user_edit_access($uid) {
  if (user_access('administer users')) {
    return TRUE;
  }
  return user_page();
}

/**
 * Custom user callback, redirect to OP.
 */
function openid_sso_user_view($account) {
  $provider = variable_get('openid_sso_provider', array());

  // Retrieve the user's openid and pass it to the OP to correctly show her
  // user account on the hub. We use a LIKE condition here to ensure that the
  // identifier retrieved matches the hub.
  if (isset($provider['url'])) {
    $identifier = db_result(db_query("SELECT authname FROM {authmap} WHERE module='openid' AND uid=%d AND authname LIKE '%s%%'", $account->uid, $provider['url']));
  }

  // Do not redirect to provider if identifier is set - in that case we just
  // came back from the provider.
  if (!empty($identifier) && $provider['url'] && !isset($_GET['identifier'])) {
    drupal_goto($provider['url'] .'sso/user', array('identifier' => $identifier));
  }
  else {
    drupal_goto('');
  }
}
/**
 * Page callback for initiating an authentication request. Logs out user before
 * initiation.
 *
 * This page is requested rather than the user/ page because it makes sure that
 * a user is NOT authenticated when initiating the OpenID authentication
 * request.
 */
function openid_sso_init_page() {
  openid_sso_logout();
  drupal_goto('user');
}

/**
 * Custom menu callback for user/page.
 */
function openid_sso_user_page() {
  global $user;
  if ($user->uid) {
    return user_page();
  }
  return openid_sso_request();
}

/**
 * Custom logout callback, redirects to hub.
 */
function openid_sso_logout_page() {
  openid_sso_logout();
  $provider = variable_get('openid_sso_provider', array());
  drupal_goto($provider['url'] .'sso/logout/', 'realm='. urlencode(url(NULL, array('absolute' => TRUE))));
}

/**
 * Settings form.
 */
function openid_sso_settings() {
  $provider = variable_get('openid_sso_provider', array());
  $form = array();
  $form['openid_sso_provider'] = array(
    '#type' => 'fieldset',
    '#title' => t('OpenID Provider'),
    '#description' => t('A designated OpenID Provider with Simple Sign-On support. This must be another Drupal site with OpenID Provider module and OpenID Provider SSO module installed and configured.'),
    '#tree' => TRUE,
  );
  $form['openid_sso_provider']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#description' => t('The site name of the provider.'),
    '#default_value' => $provider['name'],
  );
  $form['openid_sso_provider']['url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL'),
    '#description' => t('The full URL of the provider, must contain a trailing slash.'),
    '#default_value' => $provider['url'],
  );
  return system_settings_form($form);
}

/**
 * Guarantee a trailing slash.
 */
function openid_sso_settings_validate($form, &$form_state) {
  $form_state['values']['openid_sso_provider']['url'] = trim($form_state['values']['openid_sso_provider']['url'], '/') .'/';
}

/**
 * Request authentication.
 */
function openid_sso_request() {
  $provider = variable_get('openid_sso_provider', array());
  $front = drupal_get_normal_path(variable_get('site_frontpage', 'node'));
  $values = array(
    'openid_identifier' => $provider['url'],
    'openid.return_to' => url('openid/authenticate', array('absolute' => TRUE, 'query' => "destination=$front")),
  );
  openid_begin($values['openid_identifier'], $values['openid.return_to'], $values);
}

/**
 * Pillaged from user_logout(). Does not contain drupal_goto().
 */
function openid_sso_logout() {
  global $user;

  watchdog('user', 'Session closed for %name.', array('%name' => $user->name));

  // Destroy the current session:
  session_destroy();
  // Only variables can be passed by reference workaround.
  $null = NULL;
  user_module_invoke('logout', $null, $user);

  // Load the anonymous user
  $user = drupal_anonymous_user();
}

